@startuml MVP_Мониторинг_C1_альтернативный

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(партнер, "партнер", "партнер компьютерного зрения")
Person(дежурный, "дежурный сотрудник", "принимает решение о реакции на инциденты")
Person(аналитик, "Аналитик", "пользователь системы мониторинга")
Person(админ, "Администратор", "пользователь системы мониторинга")

System_Boundary(платформа, "АгроПром Х - платформа мониторинга") {
    System(данные_со_свиноферм, "Данные со свиноферм","Видео данные оцифровываются на месте, данный блок отображает группу ферм")
    System(оцифровка, "Система оцифровки сырых данных","Система оцифровывает потоковое видео и извлекает необходимые метрики")
    System(шина, "Агрегация и хранение данных", "Хранит информацию в показателях, я не сырых данных")
    System(оповещения, "Система оповещения", "Система оповещения об инцидентах")
    System(фронт_системы, "Система публичного доступа", "Включает сайт и мобильное приложение, так же api, права и разделение доступов")

}
Rel(данные_со_свиноферм, оцифровка, "отправляет потоковое видео")
Rel(партнер, оцифровка, "Загружает обновления")
Rel(оцифровка, шина, "Загружает оцифрованные данные")
Rel(оповещения, дежурный, "оповещает об инциденте")
Rel(шина, оповещения, "произошел инцидент")
Rel(фронт_системы, шина, "Запрашивает данные")
Rel(аналитик, фронт_системы, "анализирует данные")
Rel(админ, фронт_системы, "администрирует систему")
@enduml