@startuml MVP_Мониторинг_C1_основной

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(партнер, "партнер", "партнер компьютерного зрения")
Person(дежурный, "дежурный сотрудник", "принимает решение о реакции на инциденты")
Person(аналитик, "Аналитик", "пользователь системы мониторинга")
Person(админ, "Администратор", "пользователь системы мониторинга")

System_Boundary(платформа, "АгроПром Х - платформа мониторинга") {
    Container_Boundary(данные_со_свиноферм, "Данные со свиноферм","", "Видео данные оцифровываются на месте и извлекает необходимые метрики, данный блок отображает группу ферм"){
        Container(камеры, "Камеры")
        Container(обработка_видео, "Модуль обработки видео потока", "Python")
        Rel(камеры, обработка_видео, "передача видео по локальной сети")   
        Container(очередь_событий_фермы, "Очередь событий", "Artemis")
        Rel(обработка_видео, очередь_событий_фермы, "отправляет оцифрованные данные")        
        Container(датчики, "Контроллер датчиков", "", "датчики уровня воды, еды")
        Rel(датчики, очередь_событий_фермы, "отправляет данные с датчиков уровня кормов")        
        Container(доставка_данных, "Доставка данных", "", "Доставка данных в центральное хранилище для обработки, включает механизмы контроля доставки и повторной отправки")
        Rel(доставка_данных, очередь_событий_фермы, "подписан на изменения")
        ContainerDb(база_данных_фермы, "Локальная база данных фермы", "mysql", "Хранит локально данные")
        Rel(база_данных_фермы, очередь_событий_фермы, "подписан на изменения")
    }
    Container_Boundary(шина, "Агрегация и хранение данных", ""){
        Container(точка_поступления_данных, "API подключения для загрузки данных")
        Container(шина_данных, "Шина данных", "Kafka")
        Rel(точка_поступления_данных, шина_данных, "отправка данных")
        ContainerDb(общее_хранилище, "Главное хранилище данных", "PostgreSQL")
        Rel(общее_хранилище, шина_данных, "подписка на изменения")
        Container(распознавание_инцидентов, "Распознование инцидентов", "", "извлекает данные и принимает решение об инциденте")
        Rel(распознавание_инцидентов, шина_данных, "подписка на изменения")
        Container(внутренний_апи, "внутреннее апи для получения данных")
        Rel(внутренний_апи, общее_хранилище, "Запрашивает данные")
    }
    Container(обновление_зрения, "Обновление алгоритмов компьютерного зрения", "")
    Container(оповещения, "Система оповещения", "Система оповещения об инцидентах")
    Container_Boundary(фронт_системы, "Система публичного доступа", "Включает сайт и мобильное приложение, так же api, права и разделение доступов"){
        Container(api_публичный, "API подключения", "REST")
        Rel(api_публичный, внутренний_апи, "Запрашивает данные")
        Container(сайт, "Сайт", "PHP")
        Rel(сайт, внутренний_апи, "Запрашивает данные")
        Container(мобильное_приложение, "Мобильное приложение", "Kotlin")
        Rel(мобильное_приложение, api_публичный, "Запрашивает данные")
    }

}
Rel(доставка_данных, точка_поступления_данных, "отправляет оцифрованные данные", "grpc")
Rel(обновление_зрения, обработка_видео, "обновляет алгоритмы на каждой ферме")
Rel(распознавание_инцидентов, оповещения, "произошел инцидент")

Rel(оповещения, мобильное_приложение, "оповещает об инциденте")
Rel(дежурный, мобильное_приложение, "получает данные об инцидентах")
Rel(партнер, обновление_зрения, "Загружает обновления")
Rel(аналитик, сайт, "анализирует данные")
Rel(админ, сайт, "администрирует систему")
@enduml